### ISSUE TITLE
Support exchanging data

### ISSUE THREAD

**Issue by paresy** [addnab/docker-run-action#1]
Hi and thanks for your this nice action! See my post below for the solution.

**Comment by paresy** [comment]
Works awesome. You might want to document the hidden parameter 'options' :)
I am not sure if it is also possible to somehow mount $GITHUB_WORKSPACE or $RUNNER_WORKSPACE. Using the absolute path works, though.

```
    - name: Run in dart
      uses: addnab/docker-run-action@v1
      with:
        image: google/dart:2.8
        options: -v /home/runner/work/xxx/xxx:/home
        run: |
          dart --version
          cd /home
          pub get
          pub global activate webdev
          $HOME/.pub-cache/bin/webdev build --output=web:build
```

**Comment by addnab** [comment]
Thanks for the input. I've updated the docs with your suggestion.

From the link you that you've tagged, I understand how `options: -v $GITHUB_WORKSPACE:/work` would work but can't get my head around how `eval` is able to parse `${{github.workspace}}`?
