### ISSUE TITLE
Failure to mount Github volumes to container

### ISSUE THREAD

**Issue by electronjoe** [addnab/docker-run-action#11]
Thank you for the docker-run-action! It really cleans up an otherwise quite verbose `docker run` command in my workflow yml.

I spent some time exploring the missing volume mounts in the docker image spun up by docker-run-action.  I eventually recognized that your README suggests the following:

> Typical Use Case
> ...
> options: -v ${{ github.workspace }}:/work -e ABC=123

But there was no explanation for why the option is there (work-around for missing ~nominal [Container Github Mounts](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#docker-container-filesystem)?).  I'm not sure what the ABC=123 environment variable is for? For something as fundamental as github docker filesystem mounts - the use of option seems strange (they should just always be mounted, I would expect). So I had omitted this as I didn't anticipate needing atypical Github container filesystem mounts.

Below is the diagnostic debug from a GitHub action using docker-run-action.  Do you know why your action is having to use the additional volume mount (to /work) and the below volume mounts aren't working? (I do see below: `-v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/magma/magma":"/github/workspace"`).  I am attempting to turn on docker log capture to see if it gives more detail on the failure of these volume mounts. But probably you know more on this front?

**Ultimately, I would want my workflows to use nominal Github Container Mount locations - as supported by Github environment variables - and not bake in /work or other mount points that are unexpected.**

> 2021-03-13T09:21:19.7242028Z ##[command]/usr/bin/docker run --name e4c4ba00c7819a48ec8a9074eb7b6dcdbb_20fe66 --label 5588e4 --workdir /github/workspace --rm -e INPUT_IMAGE -e INPUT_RUN -e INPUT_OPTIONS -e INPUT_SHELL -e INPUT_REGISTRY -e INPUT_USERNAME -e INPUT_PASSWORD -e INPUT_DOCKER_NETWORK -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_DEBUG -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/magma/magma":"/github/workspace" 5588e4:c4ba00c7819a48ec8a9074eb7b6dcdbb

**Comment by addnab** [comment]
Hi @electronjoe,

It took a while for me to understand what you were trying to do. I've learnt a bit in the process. Didn't know problem matching was a thing

**Comment by addnab** [comment]
Hi @electronjoe,

I had to do some research to figure out what you were trying to do. I've learn a bit in the process. Didn't know problem matching was a thing 😄. 

Some points I wanted to bring up:- 
- ABC=123 is just an example for env params. The options accepts the same arguments as your `docker run` cli command.
- The github workspace is not mounted by default because I also want this action to cover another common use case - where you'd build an image in a previous step and would want to immediately run it in the same workflow.
- Whether you want the image to be mounted by default or not, it will need to be mounted somewhere. Doesn't need to be `/work`. Not sure why you'd want it mounted on `/github/workspace` but I don't see any reason why you can't do it. Just make sure the volume you're mounting accessible/exists on the host, and when you run any scripts from within the image, keep in mind you're running it on the last WORKDIR of the image, so you'll need to cd into the mounted volume before running any commands.

**Comment by electronjoe** [comment]
Hi @addnab! Thanks for the reply!

I'll be removing the ABC=123 environment variable from my GH Action lol.

Ultimately what I'm concerned about above - and haven't root caused.  The docker command being passed is asking for volumes to be mounted from GitHub's workspace.  E.g. see the `-v "/home/runner/work/magma/magma":"/github/workspace"` log line above.  Yet when I am inside the docker container started by `docker-run-actions` this volume is missing (and can be added back only by using the options args for `docker-run-application`).

**Comment by addnab** [comment]
@electronjoe Ah. I see what you mean. Yes, that's expected. Even though `docker-run-action` is a docker action that github automatically mounts volumes to, the docker image that is running inside docker (Dockerception!!) won't automatically mount those volumes again unless explicitly specified like in the README.

See https://github.com/addnab/docker-run-action/blob/a808c5419d54e52828de6529f8596b15830a3794/entrypoint.sh#L13

**Comment by addnab** [comment]
Closing this for now as it appears you've gotten your answer. Feel free to reopen this issue if you think otherwise.
