### ISSUE TITLE
How to specify volume mount?

### ISSUE THREAD

**Issue by fatso83** [addnab/docker-run-action#28]
How would I mount the local directory as a volume? I would like to run this command using the GH action, but I see no option to mount volumes.

```
docker run --rm -v "$(pwd):/app" slashmo/swiftformat
```

**Comment by tony** [comment]
I'm in the same spot, it gives me:

```
docker: Error response from daemon: create $(pwd): "$(pwd)" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
```

**Comment by tony** [comment]
@fatso83 Try this:

```
options: --rm -v ${{ github.workspace }}:/zap/wrk/:rw
```

In your case it would be: `docker run --rm -v "${{ github.workspace }}:/app" slashmo/swiftformat`

I found this via:
- https://github.com/addnab/docker-run-action/commit/6f0804dd49caf60dff3f446626c5918c65c9efa7 ([readme](https://github.com/addnab/docker-run-action/tree/v3#typical-use-case))
- https://github.com/addnab/docker-run-action/issues/5
- https://github.com/addnab/docker-run-action/issues/4

**Comment by fatso83** [comment]
Perfect! Great to see it is mentioned, but it would be even better with an explicit text. Easy to miss a small `-v` in a wall of text 😄

**Comment by fatso83** [comment]
Added a PR for this btw. Still waiting six weeks in
