### ISSUE TITLE
Retrieving artifacts from this action

### ISSUE THREAD

**Issue by mbogh** [addnab/docker-run-action#9]
Hi,

First thank you for the nice action, it worked where the container/uses approach failed.
But how would I best upload the result of doing work inside the container to either a next step or for the artifacts?

-Morten

**Comment by addnab** [comment]
Hi @mbogh,

There a couple of ways you can do this.
1. If it's a file you want to output, mount the github workspace as a volume like in the README example. Any files created should be available in the workspace of following steps that run outside of the docker-run-action.
2. If you want to output parameters, you can also do that by echoing the output parameter like so https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-output-parameter

I hope that answered your question.

**Comment by mbogh** [comment]
Problem with the volume mounting is permissions. The image I use, does not use the root user and it fails to write to the volume. I ended up simply adding ` --user 0:0` as a workaround :(

But thanks 🦦

**Comment by addnab** [comment]
@mbogh That's odd. Good to know that you've found a workaround. I'm just curious - if the docker image is public, can you share it with me and also the workflow steps with your fix? I'd like to test it and maybe document it in the README.
